spring:
  #thymeleaf配置，其中有一些是默认的，可以不做配置
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  #druid配置，数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456789
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3  #s
    password: 123456
#mybatis配置
mybatis:
  type-aliases-package: miaosha.demo.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:miaosha/demo/dao/*.xml



